// ---------------------------------------------------------------------------
// Bitlab — AI track. Easy -> medium, gamified, NO code required.
// Same shape as the SQL track: animated explainer + interactive games/quizzes.
// AI lessons use only non-SQL challenge types (match / tap / order / choice / predict).
// ---------------------------------------------------------------------------
import type { Unit } from "./curriculum";

export const AI_CURRICULUM: Unit[] = [
  {
    id: "au1",
    index: 1,
    title: "Meet AI",
    blurb: "What AI is and how it learns.",
    color: "#cbe94b",
    lessons: [
      {
        id: "au1l1",
        unitId: "au1",
        title: "AI is a smart guesser",
        subtitle: "Learns from examples, then guesses",
        concept: "AI is a computer that learns patterns from lots of examples, then makes a smart guess about something new.",
        explainer: {
          theme: "ai",
          scenes: [
            { text: "Hi! I'm Bit. Let's meet AI.", anim: "talk" },
            { text: "AI is a computer that learns from examples.", anim: "data" },
            { text: "It spots patterns, then makes a smart guess.", anim: "learn" },
            { text: "Show it lots of cats — it learns what a cat looks like.", anim: "learn" },
            { text: "New photo? It guesses: cat or not. Let's play!", anim: "guess" },
          ],
        },
        challenges: [
          {
            id: "au1l1g1",
            type: "match",
            prompt: "Match each word to what it means. Tap one, then its partner.",
            pairs: [
              { left: "AI", right: "a smart guesser" },
              { left: "example", right: "something AI learns from" },
              { left: "guess", right: "AI's answer" },
            ],
            hint: "AI learns from examples and gives a guess.",
            explain: "AI learns from examples and makes guesses. That's the whole idea!",
            xp: 20,
          },
          {
            id: "au1l1c1",
            type: "choice",
            prompt: "What does AI mainly do?",
            options: [
              { label: "Finds patterns and makes smart guesses", correct: true },
              { label: "Never ever makes a mistake", correct: false },
              { label: "Thinks exactly like a human brain", correct: false },
            ],
            hint: "AI is a pattern-spotter, not a perfect genius.",
            explain: "AI finds patterns in examples and guesses. It can be wrong — it's guessing!",
            xp: 15,
          },
          {
            id: "au1l1g2",
            type: "tap",
            prompt: "Tap the things AI could LEARN from (its examples).",
            rows: [
              { label: "100 cat photos", match: true },
              { label: "one random click", match: false },
              { label: "1000 movie reviews", match: true },
              { label: "an empty page", match: false },
              { label: "emails marked 'spam'", match: true },
              { label: "a blank form", match: false },
            ],
            hint: "Examples are lots of real things with useful info in them.",
            explain: "AI learns from many real examples — photos, reviews, labelled emails. Empty things teach it nothing.",
            xp: 25,
          },
        ],
      },
      {
        id: "au1l2",
        unitId: "au1",
        title: "Data is AI's food",
        subtitle: "Examples AI eats to learn",
        concept: "Data means examples — photos, texts, numbers. More good data makes AI smarter. Bad data makes it worse.",
        explainer: {
          theme: "ai",
          scenes: [
            { text: "AI learns from DATA.", anim: "talk" },
            { text: "Data = examples: photos, texts, numbers.", anim: "data" },
            { text: "More good data = a smarter AI.", anim: "learn" },
            { text: "Bad or messy data = bad guesses.", anim: "think" },
            { text: "Feed it well and it learns well!", anim: "star" },
          ],
        },
        challenges: [
          {
            id: "au1l2c1",
            type: "choice",
            prompt: "What is 'data' for an AI?",
            options: [
              { label: "The examples it learns from", correct: true },
              { label: "A type of robot", correct: false },
              { label: "The screen it lives on", correct: false },
            ],
            hint: "Think of data as AI's food — the examples it eats to learn.",
            explain: "Data is the examples AI learns from. No data, no learning.",
            xp: 15,
          },
          {
            id: "au1l2g1",
            type: "match",
            prompt: "Match each example to the kind of data it is.",
            pairs: [
              { left: "a photo", right: "image data" },
              { left: "a review", right: "text data" },
              { left: "a temperature", right: "number data" },
            ],
            hint: "Data can be pictures, words, or numbers.",
            explain: "Images, text and numbers are all data AI can learn from.",
            xp: 20,
          },
          {
            id: "au1l2g2",
            type: "tap",
            prompt: "Tap everything that counts as good DATA for learning.",
            rows: [
              { label: "labelled apple & banana photos", match: true },
              { label: "random screen noise", match: false },
              { label: "1000 song reviews", match: true },
              { label: "a broken file", match: false },
              { label: "daily temperatures for a year", match: true },
            ],
            hint: "Good data is real examples with clear info.",
            explain: "Clear, labelled, real examples are great data. Noise and broken files aren't.",
            xp: 25,
          },
        ],
      },
      {
        id: "au1l3",
        unitId: "au1",
        title: "Learn, then guess",
        subtitle: "Training vs predicting",
        concept: "AI works in two steps: first it TRAINS (learns from examples), then it PREDICTS (guesses about something new).",
        explainer: {
          theme: "ai",
          scenes: [
            { text: "AI works in two steps.", anim: "talk" },
            { text: "Step 1: it TRAINS — it studies the examples.", anim: "data" },
            { text: "It finds the patterns inside them.", anim: "learn" },
            { text: "Step 2: you give it something new.", anim: "think" },
            { text: "It PREDICTS — makes its best guess. Let's go!", anim: "guess" },
          ],
        },
        challenges: [
          {
            id: "au1l3g1",
            type: "order",
            prompt: "Put the steps of how AI works in the right order.",
            items: ["Collect examples (data)", "AI trains (learns patterns)", "Give it something new", "AI predicts (guesses)"],
            hint: "First it learns from data, then it guesses about new things.",
            explain: "Collect data → train → show something new → predict. That's every AI!",
            xp: 25,
          },
          {
            id: "au1l3c1",
            type: "choice",
            prompt: "Which happens FIRST?",
            options: [
              { label: "Training on examples", correct: true },
              { label: "Making a guess", correct: false },
              { label: "Nothing — AI just knows", correct: false },
            ],
            hint: "It has to learn before it can guess.",
            explain: "Training comes first. Only after learning can AI predict.",
            xp: 15,
          },
          {
            id: "au1l3c2",
            type: "predict",
            prompt: "You trained an AI only on DOG photos, then showed it a cat. What happens?",
            options: [
              { label: "It guesses using dog patterns — and may be wrong", correct: true },
              { label: "It instantly knows everything about cats", correct: false },
              { label: "It breaks the computer", correct: false },
            ],
            hint: "AI only knows the patterns it was trained on.",
            explain: "AI only learned dogs, so it guesses with dog patterns — often wrong. Training data matters!",
            xp: 20,
          },
        ],
      },
    ],
  },
  {
    id: "au2",
    index: 2,
    title: "How AI thinks",
    blurb: "Patterns, good data, and mistakes.",
    color: "#cbe94b",
    lessons: [
      {
        id: "au2l1",
        unitId: "au2",
        title: "Spotting patterns",
        subtitle: "How AI recognises things",
        concept: "AI recognises things by the patterns it saw in many examples — like the shapes and colours in cat photos.",
        explainer: {
          theme: "ai",
          scenes: [
            { text: "How does AI know a cat is a cat?", anim: "talk" },
            { text: "It saw thousands of cat photos.", anim: "data" },
            { text: "It learned the patterns — ears, whiskers, shape.", anim: "learn" },
            { text: "New photo? It checks for those patterns.", anim: "think" },
            { text: "Match found → 'that's a cat!' Let's try.", anim: "guess" },
          ],
        },
        challenges: [
          {
            id: "au2l1g1",
            type: "tap",
            prompt: "You built a CAT detector. Tap everything it should label 'cat'.",
            rows: [
              { label: "🐱 kitten", match: true },
              { label: "🐶 puppy", match: false },
              { label: "🐈 cat", match: true },
              { label: "🚗 car", match: false },
              { label: "🐈‍⬛ black cat", match: true },
              { label: "🍎 apple", match: false },
            ],
            hint: "Only the cats! Dogs, cars and apples are not cats.",
            explain: "Your detector looks for cat patterns — so only the cats get the 'cat' label.",
            xp: 25,
          },
          {
            id: "au2l1c1",
            type: "choice",
            prompt: "How does AI recognise a cat?",
            options: [
              { label: "By patterns it saw in many cat photos", correct: true },
              { label: "By reading the cat's mind", correct: false },
              { label: "By asking the cat", correct: false },
            ],
            hint: "It learned patterns from lots of examples.",
            explain: "AI matches new photos against patterns it learned from many examples.",
            xp: 15,
          },
        ],
      },
      {
        id: "au2l2",
        unitId: "au2",
        title: "Good data, bad data",
        subtitle: "Garbage in, garbage out",
        concept: "AI is only as good as its examples. Clean, varied data makes good guesses. Messy or narrow data makes bad ones.",
        explainer: {
          theme: "ai",
          scenes: [
            { text: "AI copies whatever data you give it.", anim: "talk" },
            { text: "Good, clean examples → good guesses.", anim: "learn" },
            { text: "Messy or wrong examples → bad guesses.", anim: "think" },
            { text: "People say: garbage in, garbage out.", anim: "data" },
            { text: "So pick your data carefully!", anim: "star" },
          ],
        },
        challenges: [
          {
            id: "au2l2c1",
            type: "choice",
            prompt: "You train a photo app on ONLY blurry pictures. What happens?",
            options: [
              { label: "It struggles with clear pictures", correct: true },
              { label: "It becomes perfect at everything", correct: false },
              { label: "Nothing changes", correct: false },
            ],
            hint: "AI learns from what it sees — only blurry, so it only knows blurry.",
            explain: "Train on blurry only, and clear photos confuse it. Varied data matters.",
            xp: 20,
          },
          {
            id: "au2l2g1",
            type: "tap",
            prompt: "Tap the GOOD training data for a fruit-spotting app.",
            rows: [
              { label: "clear, labelled fruit photos", match: true },
              { label: "random static noise", match: false },
              { label: "many kinds of apples & bananas", match: true },
              { label: "photos of cars", match: false },
              { label: "blurry, unlabelled blobs", match: false },
            ],
            hint: "Good data is clear, labelled, and about fruit.",
            explain: "Clear, labelled, varied fruit photos = good data. Cars and noise = bad data.",
            xp: 25,
          },
          {
            id: "au2l2g2",
            type: "match",
            prompt: "Match the data to the result.",
            pairs: [
              { left: "clean, varied data", right: "good guesses" },
              { left: "messy, narrow data", right: "bad guesses" },
            ],
            hint: "Better food in, better guesses out.",
            explain: "The quality of the data decides the quality of the AI.",
            xp: 20,
          },
        ],
      },
      {
        id: "au2l3",
        unitId: "au2",
        title: "AI can be unfair (bias)",
        subtitle: "It copies the data — even the bad parts",
        concept: "AI copies patterns in its data, including unfair ones. If the data isn't fair or varied, the AI's guesses won't be either.",
        explainer: {
          theme: "ai",
          scenes: [
            { text: "AI has no opinions — it copies the data.", anim: "talk" },
            { text: "If the data is one-sided, the AI is too.", anim: "think" },
            { text: "That unfairness is called BIAS.", anim: "data" },
            { text: "Example: trained on summer only → bad in winter.", anim: "guess" },
            { text: "Fix it with varied, fair examples.", anim: "star" },
          ],
        },
        challenges: [
          {
            id: "au2l3c1",
            type: "choice",
            prompt: "An AI learned only from SUMMER photos. In winter it will…",
            options: [
              { label: "Probably guess wrong — it never saw winter", correct: true },
              { label: "Work perfectly, winter is easy", correct: false },
              { label: "Refuse to work", correct: false },
            ],
            hint: "It only knows what it was shown.",
            explain: "No winter in the data means winter confuses it. That gap is bias.",
            xp: 20,
          },
          {
            id: "au2l3c2",
            type: "predict",
            prompt: "A face app is trained on just one group of people. What's likely?",
            options: [
              { label: "It works worse for everyone else (that's bias)", correct: true },
              { label: "It works equally well for all", correct: false },
              { label: "It invents new faces", correct: false },
            ],
            hint: "Narrow data → unfair results.",
            explain: "One-sided data makes the AI unfair to groups it didn't learn from. That's bias.",
            xp: 25,
          },
          {
            id: "au2l3c3",
            type: "choice",
            prompt: "Best way to reduce bias?",
            options: [
              { label: "Use varied, fair examples of everyone", correct: true },
              { label: "Use even less data", correct: false },
              { label: "Hope for the best", correct: false },
            ],
            hint: "Fairer data → fairer AI.",
            explain: "Varied, representative data is the main fix for bias.",
            xp: 20,
          },
        ],
      },
    ],
  },
  {
    id: "au3",
    index: 3,
    title: "Talk to AI",
    blurb: "Prompts — how to ask AI well.",
    color: "#cbe94b",
    lessons: [
      {
        id: "au3l1",
        unitId: "au3",
        title: "What's a prompt?",
        subtitle: "The instruction you give AI",
        concept: "A prompt is the instruction you type to an AI. A clearer prompt gets a better answer.",
        explainer: {
          theme: "ai",
          scenes: [
            { text: "You talk to AI by typing a PROMPT.", anim: "talk" },
            { text: "A prompt is your instruction or question.", anim: "data" },
            { text: "Clear prompt → good answer.", anim: "learn" },
            { text: "Vague prompt → confused answer.", anim: "think" },
            { text: "Let's learn to ask well!", anim: "star" },
          ],
        },
        challenges: [
          {
            id: "au3l1g1",
            type: "match",
            prompt: "Match the idea to its meaning.",
            pairs: [
              { left: "prompt", right: "what you ask the AI" },
              { left: "clear prompt", right: "gets a better answer" },
              { left: "vague prompt", right: "gets a confused answer" },
            ],
            hint: "A prompt is your instruction to the AI.",
            explain: "A prompt is what you ask; clearer asks get better answers.",
            xp: 20,
          },
          {
            id: "au3l1c1",
            type: "choice",
            prompt: "A prompt is…",
            options: [
              { label: "The instruction you give the AI", correct: true },
              { label: "A kind of computer chip", correct: false },
              { label: "The AI's name", correct: false },
            ],
            hint: "It's what YOU type to the AI.",
            explain: "A prompt is the instruction or question you give the AI.",
            xp: 15,
          },
        ],
      },
      {
        id: "au3l2",
        unitId: "au3",
        title: "Good prompts",
        subtitle: "Clear and specific wins",
        concept: "Good prompts are clear and specific: say what you want, for whom, and how long or what style.",
        explainer: {
          theme: "ai",
          scenes: [
            { text: "What makes a prompt GOOD?", anim: "talk" },
            { text: "Be clear: say exactly what you want.", anim: "learn" },
            { text: "Be specific: who is it for? how long?", anim: "think" },
            { text: "'poem' is weak. 'a 3-line poem about the sea' is strong.", anim: "data" },
            { text: "Clear + specific = great answers!", anim: "star" },
          ],
        },
        challenges: [
          {
            id: "au3l2c1",
            type: "choice",
            prompt: "Which is the BETTER prompt?",
            options: [
              { label: "Write a 3-line birthday poem for my mom", correct: true },
              { label: "poem", correct: false },
            ],
            hint: "The better prompt says what, for whom, and how long.",
            explain: "Specific prompts (what, for whom, how long) get much better answers.",
            xp: 20,
          },
          {
            id: "au3l2c2",
            type: "choice",
            prompt: "A good prompt is…",
            options: [
              { label: "Clear and specific", correct: true },
              { label: "As short and vague as possible", correct: false },
              { label: "Full of spelling mistakes", correct: false },
            ],
            hint: "Say exactly what you want.",
            explain: "Clear + specific prompts guide the AI to the answer you actually want.",
            xp: 15,
          },
          {
            id: "au3l2g1",
            type: "tap",
            prompt: "Tap the GOOD prompts (clear and specific).",
            rows: [
              { label: "Explain gravity to a 10-year-old in 3 lines", match: true },
              { label: "stuff", match: false },
              { label: "List 3 healthy breakfast ideas", match: true },
              { label: "do the thing", match: false },
              { label: "Summarise this story in one sentence", match: true },
            ],
            hint: "Good prompts are clear and say exactly what you want.",
            explain: "Clear, specific asks are good prompts. 'stuff' and 'do the thing' are too vague.",
            xp: 25,
          },
        ],
      },
      {
        id: "au3l3",
        unitId: "au3",
        title: "Build a prompt",
        subtitle: "Put the pieces in order",
        concept: "A strong prompt often has: an action word, the thing, the topic, and the style. Arrange them clearly.",
        explainer: {
          theme: "ai",
          scenes: [
            { text: "Let's build a prompt, piece by piece.", anim: "talk" },
            { text: "Start with an action: 'Write', 'Explain', 'List'.", anim: "data" },
            { text: "Add the thing: 'a 3-line poem'.", anim: "learn" },
            { text: "Add the topic: 'about the ocean'.", anim: "think" },
            { text: "Put them in order — you've built a prompt!", anim: "star" },
          ],
        },
        challenges: [
          {
            id: "au3l3g1",
            type: "order",
            prompt: "Arrange the pieces into a clear prompt.",
            items: ["Write", "a 3-line poem", "about", "the ocean"],
            hint: "Start with the action word, then what, then the topic.",
            explain: "Action → what → topic. 'Write a 3-line poem about the ocean' is a clear prompt!",
            xp: 25,
          },
          {
            id: "au3l3g2",
            type: "order",
            prompt: "Build another clear prompt from these pieces.",
            items: ["Explain", "photosynthesis", "to a beginner", "in simple words"],
            hint: "Action first, then the topic, then who it's for and the style.",
            explain: "'Explain photosynthesis to a beginner in simple words' — clear and specific!",
            xp: 30,
          },
          {
            id: "au3l3c1",
            type: "choice",
            prompt: "Adding 'in simple words' to a prompt makes the answer…",
            options: [
              { label: "Easier to understand", correct: true },
              { label: "Longer and harder", correct: false },
              { label: "Totally random", correct: false },
            ],
            hint: "You're telling the AI the style you want.",
            explain: "Style hints like 'in simple words' shape the answer to fit you.",
            xp: 15,
          },
        ],
      },
    ],
  },
];
